### PR TITLE
use markdown editor for asset description

### PR DESCRIPTION
**Pull request by phoebus-84**
resolve: #17 

need https://github.com/dyne/zenflows-crypto/pull/6 to work properly

- add MarkDown editor to brickroom
- parse html in asset detail page
- save tags to db

### CODE REVIEW

**Review by puria — COMMENTED** [review]
Could we save the markdown text in place of the HTML?
Can you show the correct saved tags inside the asset table and in the asset/[id] page?

**Comment by puria** [comment]
tests to be added...
create an asset with some bold text:

- [ ] verify that the <strong> or <b> is shown in the asset/[id] page
- [ ] verify that the tags are correctly shown

**Comment by phoebus-84** [comment]
>Could we save the markdown text in place of the HTML?
yep.. np, I will handle it
>Can you show the correct saved tags inside the asset table and in the asset/[id] page?
Nope.. until there are not track and trace on the backend we cant

**Comment by puria** [comment]
> tests to be added... create an asset with some bold text:
> 
> * [x]  verify that the `<strong>` or `<b>` is shown in the asset/[id] page
> * [ ]  verify that the tags are correctly shown

ooops sorry, maybe I should have been more explicit... I want to see cypress tests and code here 😜

**Pull request merged**
