### PR TITLE
add geocoding

### PR DESCRIPTION
**Pull request by phoebus-84**
resolve: #28 
- select adress whit geocodind function
- use react-select for add contributors
- some rect-select theme customization

### CODE REVIEW

**Review by puria — APPROVED** [review]

**Comment by bbtgnn** [comment]
@phoebus-84  While testing `/create_asset` page I've found a bug.
As soon as I open the page, it gives me this error: 

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```
```
{"error":"Unauthorized","error_description":"Illegal API key id"}
```
Looks like the autocomplete is not working. Am I missing something?

**Comment by bbtgnn** [comment]
@phoebus-84 also, there's a small UI fix to do: the placeholder text overflows the container
Schermata 2022-09-30 alle 12 27 58

**Comment by phoebus-84** [comment]
yep..  this is because you don't have the api key in the env file..

> @phoebus-84 While testing `/create_asset` page I've found a bug. As soon as I open the page, it gives me this error:
> 
> ```
> Failed to load resource: the server responded with a status of 401 (Unauthorized)
> ```
> 
> ```
> {"error":"Unauthorized","error_description":"Illegal API key id"}
> ```
> 
> Looks like the autocomplete is not working. Am I missing something?

**Comment by bbtgnn** [comment]
Solved

**Comment by phoebus-84** [comment]
> 

https://github.com/dyne/interfacer-gui/commit/ace538cdfa06b3f9e823ca6c8d9ce69c29c65e04 fixes the placeholder...

**Pull request merged**
